Add Code of Conduct v_01
brainhackorg/brainhack_jupyter_book pull request #27
Opened 2021-02-06 20:19 UTC by complexbrains

2021-02-08 15:59 UTC, SamGuay commented
Is this file an example of a CoC or the actual CoC? 

Asking since these parts 
> ... administrators via  [REQUIRES CONTACT POINTS] ... 
> ... the admins by email at [EMAIL ADDRESS HERE]. ...

feel odd if not only an example.

2021-02-08 17:29 UTC, complexbrains commented
@SamGuay a bit of both, that needs to be decided for sure, but we can only give brainhack email for now until we will set a better workflow as BHG team in the next year.

2021-02-11 14:58 UTC, SamGuay requested changes
I've made mostly minor comments / changes. However, we'll have to think about the issue I raised earlier (re: contact points). Also the CoC keeps mentioning _community leaders_ but who are they? As far as I am concerned, I think some people should be in charge of CoC, otherwise who could take actions, anyone who deems themselves a _community leader_? For example, is a project lead a community leader? Are the brainhack _founders_ the only community leaders? 

I think the _community leaders_ should be representative of the brainhack community globally. 

PS: For the sake of consistency, I put back all the lines that were cut at ~80 characters since many were not. We may want to parse them properly once we have a final version. 

(It won't change a thing in how this is appear in the book, I know :grin:)

2021-02-11 14:58 UTC, SamGuay commented on brainhack_book/code_of_conduct.md
> +community itself.
```suggestion
As part of the open science community, we must promote and advocate inclusivity through a welcoming environment, giving voice to underrepresented and marginalized people, and creating means and tools in building up a healthy community. Understanding this assertion, this Code of Conduct is the expression of these values, and intends to foster a space of kindness, cooperation and empathy within this particular project and the community itself.
```

2021-02-11 14:58 UTC, SamGuay commented on brainhack_book/code_of_conduct.md
> +This Code of Conduct is applicable to all of the community spaces, including public channels, private channel and conversations, both in the case of online and offline communications and contribution
```suggestion
This Code of Conduct is applicable to all of the community spaces, including public channels, private channels and conversations, both in the case of online and offline communications and contributions to the project. In the case of the violation of the Code of Conduct, the project contributors and the community members will have the right to reevaluate the situation and sanction or expel those who created discomfort or violation. 
```

> In the case of the violation of the Code of Conduct, the project contributors and the community members will have the right to reevaluate the situation and sanction or expel those who created discomfort or violation. 

I am not too sure about this sentence. What do you mean specifically? Should this sentence be in some section below (eg, Enforcement..?)

2021-02-11 14:58 UTC, SamGuay commented on brainhack_book/code_of_conduct.md
> +size, visible or invisible disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, r
```suggestion
We as members, contributors, and leaders pledge to make participation in our community a harassment-free experience for everyone, regardless of age, body size, visible or invisible disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation, among others. 
```

2021-02-11 14:58 UTC, SamGuay commented on brainhack_book/code_of_conduct.md
> +diverse, inclusive, and healthy community.
```suggestion
We pledge to act and interact in ways that contribute to an open, welcoming, diverse, inclusive, and healthy community.
```

2021-02-11 14:58 UTC, SamGuay commented on brainhack_book/code_of_conduct.md
> +We aim to create a welcoming environment in which the members from any diverse background can interact in positive and affirming way. For that basis we follow the below goals throughout our interacti
```suggestion
We aim to create a welcoming environment in which members from any diverse background can interact in a positive and affirming way. On that basis, we follow the below goals throughout our interactions:
```

2021-02-11 14:58 UTC, SamGuay commented on brainhack_book/code_of_conduct.md
> +* Offensive comments related to gender, gender identity and expression, sexual orientation, disability, mental illness, neuro(a)typicality, physical appearance, pregnancy status, veteran status, poli
```suggestion
* Offensive comments related to gender, gender identity and expression, sexual orientation, disability, mental illness, neuro(a)typicality, physical appearance, pregnancy status, veteran status, political affiliation, marital status, body size, age, race, national origin, ethnic origin, nationality, immigration status, language, religion or lack thereof, or other identity markers. This includes anti-Indigenous/Nativeness and anti-Blackness.
```

2021-02-11 14:58 UTC, SamGuay commented on brainhack_book/code_of_conduct.md
> +If you have questions or concerns about these issues please feel free to contact [REQUIRES CONTACT POINTS] and share your opinions and suggestions.
We need to find a solution regarding who and what email address people can reach.

2021-02-11 14:58 UTC, SamGuay commented on brainhack_book/code_of_conduct.md
> +If you are being harassed by a member of our community, notice that someone else is being harassed, or have any other concerns, please contact the administrators via  [REQUIRES CONTACT POINTS]. If th
Same as the previous comment, `[REQUIRES CONTACT POINTS]` needs to be determined.

2021-02-11 14:58 UTC, SamGuay commented on brainhack_book/code_of_conduct.md
> +In order to protect volunteers from abuse and burnout, we reserve the right to reject any report we believe to have been made in bad faith. Reports intended to silence legitimate criticism may be del
```suggestion
The admin team will respond to any complaint as promptly as possible we can. If you do not get a timely response (for example, if no admins are currently online), please put your personal safety and well-being first, and consider logging out and/or contacting the admins by email at [EMAIL ADDRESS HERE].

This Code of Conduct applies to our community's spaces, but if you are being harassed by a member of our community outside our spaces, we still want to know about it. We will take all good-faith reports of harassment by our members, especially the administrators, seriously. This includes harassment outside our spaces and harassment that took place at any point in time. The abuse team reserves the right to exclude people from the community based on their past behaviour, including behaviour outside of our spaces and behaviour towards people who are not in this community.

To protect volunteers from abuse and burnout, we reserve the right to reject any report we believe in having been made in bad faith. Reports intended to silence legitimate criticism may be deleted without response.
```

`[EMAIL...]` needs to be addressed here too..

2021-02-11 14:58 UTC, SamGuay commented on brainhack_book/code_of_conduct.md
> +The project leaders have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct, and
```suggestion
## Enforcement Responsibilities

The project leaders are responsible for clarifying and enforcing the standards of acceptable behaviour. They will take appropriate and fair corrective action in response to any behaviour that they deem inappropriate, threatening, offensive, or harmful.

The project leaders have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct and will communicate reasons for moderation decisions when appropriate.
```

2021-02-11 14:58 UTC, SamGuay commented on brainhack_book/code_of_conduct.md
> +Every code of conduct violation report will be treated with seriousness and care. If a member's immediate safety and security is threatened, an individual admin may take any action that they deem app
```suggestion
Every code of conduct violation report will be treated with seriousness and care. If a member's immediate safety and security is threatened, an individual admin may take any action that they deem appropriate, up to and including temporarily banning the offender from the community. In less urgent situations, at least two admins will discuss the offense and mutually decide a suitable response that will be shared with the offender privately. Whatever the resolution they decide upon, the admins' decision in a violation case will be considered final.
```

2021-02-11 14:58 UTC, SamGuay commented on brainhack_book/code_of_conduct.md
> +We will respect confidentiality requests for the purpose of protecting victims of abuse. At our discretion, we may publicly name a person about whom we've received harassment complaints, or privately
```suggestion
We will respect confidentiality requests to protect victims of abuse. At our discretion, we may publicly name a person about whom we've received harassment complaints or privately warn third parties about them if we believe that doing so will increase the safety of our members or the general public. We will not name harassment victims without their affirmative consent.
```

2021-02-11 14:58 UTC, SamGuay commented on brainhack_book/code_of_conduct.md
> +Community leaders will follow the Community Impact Guideline in determining the consequences for any action they deem in violation of this Code of Conduct:
Where can we find Brainhack's _Community Impact Guideline_?

2021-02-11 14:58 UTC, SamGuay commented on brainhack_book/code_of_conduct.md
> +### Correction
What do you mean by Correction?

2021-02-11 14:58 UTC, SamGuay commented on brainhack_book/code_of_conduct.md
> +unprofessional or unwelcome in the community.
```suggestion
**Community Impact**: Use of inappropriate language or other behaviour deemed unprofessional or unwelcome in the community.
```

2021-02-11 14:58 UTC, SamGuay commented on brainhack_book/code_of_conduct.md
> +individual, or aggression toward or disparagement of classes of individuals.
```suggestion
**Community Impact**: Demonstrating a pattern of violation of community standards, including sustained inappropriate behaviour, harassment of an individual, or aggression toward or disparagement of classes of individuals.
```

2021-02-11 14:58 UTC, SamGuay commented on brainhack_book/code_of_conduct.md
> +**Consequence**: A ban from any sort of public interaction within the community and identification of the participant as a harasser to other members or to the general public.
```suggestion
**Consequence**: A ban from any sort of public interaction within the community and identification of the participant as a harasser to other members or the general public.
```

2021-02-11 14:58 UTC, SamGuay commented on brainhack_book/code_of_conduct.md
> +Participants asked to stop any harassing behaviour are expected to comply immediately. If a participant engages in harassing behaviour, the administrators may take any action they deem appropriate, u
```suggestion
Participants asked to stop any harassing behaviour are expected to comply immediately. If a participant engages in harassing behaviour, the administrators may take any action they deem appropriate, including expulsion from the community and identifying the participant as a harasser to other members. At the discretion of the admins or by request, one or more of the parties involved may request to discuss the violation and how to avoid similar situations in the future.
```

2021-02-11 14:58 UTC, SamGuay commented on brainhack_book/code_of_conduct.md
> +This Code of Conduct is adapted from the [Contributor Covenant Code of Conduct v2.0][contributorcovenant-coc], [LGBTQ in Tech community code of conduct](http://lgbtq.technology/coc.html). and from th
```suggestion
This Code of Conduct is adapted from the [Contributor Covenant Code of Conduct v2.0][contributorcovenant-coc], [LGBTQ in Tech community code of conduct](http://lgbtq.technology/coc.html). and from the [Django Project Code of Conduct][django-coc]. Community Impact Guideline was inspired by [Mozilla's code of conduct enforcement ladder][mozilla-coc]
```

2021-02-12 11:56 UTC, Remi-Gau commented
> I think the _community leaders_ should be representative of the brainhack community globally.

that might be hard in practice, no? 

shouldn't it be more someone who is closely involved in this jupyter book project?

2021-02-12 12:34 UTC, htwangtw commented
I agree with @Remi-Gau. The organisation is quite decentralised. Allocation of this kind of role by project basis is more sensible. Happy to put my name down on this one.

2021-02-12 13:32 UTC, SamGuay commented
I agree with you, @Remi-Gau. When I reviewed the CoC, I was (still am) not sure whether this CoC was only for the JB or the _official_ BH CoC. Thus, my comment. 

In the case it's only for the JB, then it makes sense that it should be people close to the project.

2021-02-12 14:02 UTC, complexbrains commented
Yes, actually this is for the book for sure, for the organization it needs many additional reviewing processes by lawyers we do not go there for sure. So maybe in the text somewhere we can indicate it clearly to remove the confusion. 

I am also volunteering for the CoC admin group so I will put @htwangtw and my handles initially as the point of contacts and will move on from there then.

2021-02-24 16:11 UTC, closed without merging