ADD PR templae
brainhackorg/brainhack_jupyter_book pull request #66
Opened 2021-03-18 17:35 UTC by htwangtw

Closes #56 

* add PR template
* description related to data files and relevant rules

2021-03-18 17:40 UTC, SamGuay requested changes

2021-03-18 17:40 UTC, SamGuay commented on .github/pull_request_template.md
> +Genral acknowledgements: `data/acknowledgments/acknowledgments.csv`
```suggestion
General acknowledgements: `data/acknowledgments/acknowledgments.csv`
```

2021-03-18 17:40 UTC, SamGuay commented on .github/pull_request_template.md
> +what they should be looking for when they review the pull request. -->
I think there is a missing word in: 
> .... consider it a note to the `is` to indicate

2021-03-18 17:45 UTC, htwangtw commented on .github/pull_request_template.md
> +Genral acknowledgements: `data/acknowledgments/acknowledgments.csv`
Done!

2021-03-18 17:58 UTC, SamGuay approved these changes
All good now! :)

2021-03-18 18:00 UTC, shawnrhoads approved these changes
LGTM!

2021-03-22 21:42 UTC, anibalsolon approved these changes
Sorry for the delay here- Looks great! 🧸

If people keep skipping the commented content and submit manuscript edits, we can try later to upper-caps this part in the comment.

2021-03-22 21:51 UTC, merged